import importlib.util
from pathlib import Path

spec = importlib.util.spec_from_file_location(
    "ingest_external", Path(__file__).resolve().parent.parent / "pipeline" / "10_ingest_external.py")
ext = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ext)


def test_clean_chat_text_drops_media_placeholders():
    assert ext.clean_chat_text("<audio> we said yes to the pricing") == "we said yes to the pricing"
    assert ext.clean_chat_text("<image>") == ""


def test_clean_email_body_keeps_only_what_was_typed():
    body = ("No worries, I'll take a look tomorrow morning.\n\n"
            "Chip\n\nOn Mon, Mar 2, 2026 at 9:00 AM Someone <s@x.com> wrote:\n> the old thread\n> more")
    assert ext.clean_email_body(body) == "No worries, I'll take a look tomorrow morning."
    body = "Done, pushed to production.\n-- \nCiprian Rarau\nFounder"
    assert ext.clean_email_body(body) == "Done, pushed to production."
    body = ("Done. Thx\n\n[image: image.png]\n\nOn Wed, Aug 26, 2026 at 5:02 PM Someone <\ns@x.com> wrote:\n> old")
    assert ext.clean_email_body(body) == "Done. Thx"
    assert ext.clean_email_body("This message was automatically generated by Gmail.") == ""
    body = "<div>Merci pour hier.<br>On se parle lundi.</div>"
    assert ext.clean_email_body(body) == "Merci pour hier.\nOn se parle lundi."


def test_make_row_skips_fragments_and_tags_source():
    assert ext.make_row(id_="wa:1", source="whatsapp", ctx="personal_chat", app="whatsapp", url="",
                        ts_iso="2026-01-01 00:00:00.000 +00:00", text="ok") is None
    row = ext.make_row(id_="wa:2", source="whatsapp", ctx="personal_chat", app="whatsapp", url="",
                       ts_iso="2026-01-01 00:00:00.000 +00:00", text="I will look at it tomorrow morning")
    assert row["source"] == "whatsapp" and row["words"] == 7 and row["edited"] is False
    assert row["lang"] == "en"


def test_client_authored_rejects_server_minted_ids():
    assert ext.client_authored("<CAF+abc@mail.gmail.com>")
    assert ext.client_authored("<SJ0PR14MB7440.x@SJ0PR14MB7440.namprd14.prod.outlook.com>")
    assert ext.client_authored("<anything@gmail.com>", mailer="iPhone Mail (23B85)")
    assert not ext.client_authored("<1234567890.abc@gmail.com>")
    assert not ext.client_authored("<xyz@mx.google.com>")
    assert not ext.client_authored(None)
