#!/usr/bin/env python3
"""10_ingest_external.py - add the user's typed messages to the corpus.

The dictation corpus is 83% instructions to AI tools. The rows that carry the
user's voice to other people are a small slice, and it shrinks as more work
moves into agent sessions. Messages the user typed to people (WhatsApp, sent
email) are the same voice, so they join the same collection, tagged by
`source`, and the cadence retrieval treats them as human-facing rows.

Adapters:
  --whatsapp            the feeds.sqlite archive kept by ideaplaces-devops/feeds
  --gmail-work USER     a Google Workspace mailbox via the delegated service
                        account (ideaplaces-devops/google-workspace/_lib.py)
  --gmail-personal      the personal Gmail through the `gmail` IMAP tool

Idempotent by id: rows already in history.jsonl are skipped, rows already in
Chroma are not re-embedded. Typed text is not passed through the mishearing
glossary (corpus.enrich handles that by source).

    python pipeline/10_ingest_external.py --whatsapp
    python pipeline/10_ingest_external.py --gmail-work chip@example.com --since-days 400
"""

from __future__ import annotations

import argparse
import base64
import importlib.util
import json
import os
import re
import sqlite3
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import config  # noqa: E402
import corpus  # noqa: E402

MIN_WORDS_TO_KEEP = 3
BATCH = 64

FEEDS_SQLITE = Path(os.environ.get(
    "FEEDS_SQLITE_PATH", Path.home() / "ideaplaces-meta/ideaplaces-devops/feeds/data/feeds.sqlite"))
WORKSPACE_DIR = Path(os.environ.get(
    "GOOGLE_WORKSPACE_DIR", Path.home() / "ideaplaces-meta/ideaplaces-devops/google-workspace"))
GMAIL_TOOL = Path(os.environ.get("GMAIL_TOOL_PATH", Path.home() / ".claude/tools/gmail.py"))


# ---------------------------------------------------------------------------
# Shared cleaning
# ---------------------------------------------------------------------------

MEDIA_PLACEHOLDER_RE = re.compile(r"<(audio|image|video|document|sticker|contact|location)[^>]*>", re.I)
QUOTE_START_RE = re.compile(
    r"^(On .{5,120} wrote:|On (Mon|Tue|Wed|Thu|Fri|Sat|Sun),? \w{3} \d{1,2},? \d{4}.*|"
    r"Le .{5,120} a écrit\s*:|Le (lun|mar|mer|jeu|ven|sam|dim)\.? \d{1,2} .*|"
    r"-----\s*Original Message\s*-----|From:\s.+|De\s*:\s.+|>+\s?.*|Begin forwarded message:|Sent from my .+)$",
    re.I | re.M)
AUTO_BODY_RE = re.compile(r"automatically generated by Gmail|This is an automated message", re.I)
INLINE_ARTIFACT_RE = re.compile(r"\[(image|cid|attachment):[^\]]*\]", re.I)
SIGNATURE_RE = re.compile(r"^(--\s*$|__+\s*$|Best,?$|Cheers,?$|Thanks,?$|Regards,?$|Merci,?$|Chip$)", re.M)
URL_RE = re.compile(r"https?://\S+")
# Sent mail the user did not write: forwards, calendar answers, auto-replies.
SKIP_SUBJECT_RE = re.compile(
    r"^\s*(fwd?|fw|tr|wg)\s*:|^\s*(accepted|declined|tentative|tentatively accepted|invitation|updated invitation|"
    r"canceled event|automatic reply|out of office|delivery status)", re.I)


def detect_lang(text: str) -> str:
    try:
        from langdetect import DetectorFactory, detect
        DetectorFactory.seed = 0
        return detect(text)
    except Exception:
        return "unknown"


def clean_chat_text(text: str) -> str:
    text = MEDIA_PLACEHOLDER_RE.sub(" ", text or "")
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def clean_email_body(body: str) -> str:
    """Keep what the sender typed: drop quoted history, headers and signature."""
    text = corpus.strip_html(body or "") if "<" in (body or "") else (body or "")
    text = text.replace("\r\n", "\n")
    if AUTO_BODY_RE.search(text):
        return ""
    text = INLINE_ARTIFACT_RE.sub(" ", text)
    m = QUOTE_START_RE.search(text)
    if m:
        text = text[: m.start()]
    m = SIGNATURE_RE.search(text)
    if m and m.start() > 0:
        text = text[: m.start()]
    text = URL_RE.sub("", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def n_words(text: str) -> int:
    return len(text.split())


def make_row(*, id_: str, source: str, ctx: str, app: str, url: str, ts_iso: str, text: str) -> dict | None:
    text = corpus.clean_text(text)
    if n_words(text) < MIN_WORDS_TO_KEEP:
        return None
    return {
        "id": id_, "ctx": ctx, "app": app, "url": url, "ts": ts_iso,
        "lang": detect_lang(text) if n_words(text) >= 4 else "unknown",
        "duration_s": 0, "words": n_words(text), "edited": False,
        "asr_text": None, "formatted_text": None, "edited_text": None,
        "text": text, "div_score": None, "n_corrected": 0, "n_dict_repl": 0,
        "source": source,
    }


def iso_from_epoch(seconds: float) -> str:
    return datetime.fromtimestamp(seconds, tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S.000 +00:00")


# ---------------------------------------------------------------------------
# WhatsApp
# ---------------------------------------------------------------------------


def whatsapp_rows(db_path: Path, since_epoch: int | None) -> list[dict]:
    if not db_path.exists():
        print(f"WhatsApp archive not found at {db_path}")
        return []
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    sql = ("SELECT message_id, channel_name, ts, text, raw_json FROM messages "
           "WHERE source='whatsapp' AND sender_id='me' AND text IS NOT NULL AND text != ''")
    params: tuple = ()
    if since_epoch:
        sql += " AND ts >= ?"
        params = (since_epoch,)
    rows = []
    for r in conn.execute(sql, params):
        try:
            raw = json.loads(r["raw_json"] or "{}")
        except json.JSONDecodeError:
            raw = {}
        row = make_row(
            id_=f"wa:{r['message_id']}", source="whatsapp", ctx="personal_chat", app="whatsapp",
            url=f"whatsapp://{'group' if raw.get('is_group') else 'dm'}/{r['channel_name'] or ''}",
            ts_iso=iso_from_epoch(r["ts"]), text=clean_chat_text(r["text"]),
        )
        if row:
            rows.append(row)
    conn.close()
    return rows


# ---------------------------------------------------------------------------
# Gmail, Google Workspace mailbox via delegated service account
# ---------------------------------------------------------------------------


def _decode_part(data: str) -> str:
    return base64.urlsafe_b64decode(data + "=" * (-len(data) % 4)).decode("utf-8", "replace")


def _gmail_payload_text(payload: dict) -> str:
    """Prefer text/plain; fall back to text/html stripped."""
    plain, html_body = [], []

    def walk(part):
        mime = part.get("mimeType", "")
        data = (part.get("body") or {}).get("data")
        if data and mime == "text/plain":
            plain.append(_decode_part(data))
        elif data and mime == "text/html":
            html_body.append(_decode_part(data))
        for sub in part.get("parts") or []:
            walk(sub)

    walk(payload)
    return "\n".join(plain) if plain else corpus.strip_html("\n".join(html_body))


def gmail_work_rows(user: str, since_days: int, limit: int) -> list[dict]:
    sys.path.insert(0, str(WORKSPACE_DIR))
    from _lib import service  # type: ignore
    scopes = ["https://www.googleapis.com/auth/gmail.readonly"]
    gmail = service("gmail", "v1", user, scopes)
    query = f"in:sent newer_than:{since_days}d"
    rows, page_token = [], None
    while len(rows) < limit:
        resp = gmail.users().messages().list(userId="me", q=query, maxResults=100, pageToken=page_token).execute()
        for stub in resp.get("messages", []):
            msg = gmail.users().messages().get(userId="me", id=stub["id"], format="full").execute()
            headers = {h["name"].lower(): h["value"] for h in msg["payload"].get("headers", [])}
            if SKIP_SUBJECT_RE.search(headers.get("subject", "")):
                continue
            body = clean_email_body(_gmail_payload_text(msg["payload"]))
            row = make_row(
                id_=f"gm:{user}:{msg['id']}", source="gmail", ctx="email", app="gmail",
                url=f"mailto:{headers.get('to', '')}", ts_iso=iso_from_epoch(int(msg["internalDate"]) / 1000),
                text=body,
            )
            if row:
                rows.append(row)
        page_token = resp.get("nextPageToken")
        if not page_token:
            break
    return rows[:limit]


# ---------------------------------------------------------------------------
# Gmail, personal mailbox over IMAP through the `gmail` tool's helpers
# ---------------------------------------------------------------------------


def gmail_personal_rows(since_days: int, limit: int, account: str | None) -> list[dict]:
    import email as email_lib
    spec = importlib.util.spec_from_file_location("gmail_tool", GMAIL_TOOL)
    tool = importlib.util.module_from_spec(spec)
    if account:
        os.environ["GMAIL_ACCOUNT"] = account
    spec.loader.exec_module(tool)  # type: ignore[union-attr]
    conn = tool.imap_connect()
    conn.select('"[Gmail]/Sent Mail"', readonly=True)
    since = datetime.now(timezone.utc).timestamp() - since_days * 86400
    since_str = datetime.fromtimestamp(since, tz=timezone.utc).strftime("%d-%b-%Y")
    ok, data = conn.uid("SEARCH", None, f"(SINCE {since_str})")
    uids = data[0].split() if ok == "OK" and data and data[0] else []
    rows = []
    label = account or "personal"
    for uid in uids[-limit:]:
        ok, fetched = conn.uid("FETCH", uid, "(BODY.PEEK[])")
        if ok != "OK" or not fetched or fetched[0] is None:
            continue
        msg = email_lib.message_from_bytes(fetched[0][1])
        if SKIP_SUBJECT_RE.search(str(tool.dh(msg.get("Subject")) or "")):
            continue
        body = clean_email_body(tool.get_body(msg))
        try:
            ts = email_lib.utils.parsedate_to_datetime(msg.get("Date")).timestamp()
        except Exception:
            ts = time.time()
        row = make_row(
            id_=f"gm:{label}:{uid.decode()}", source="gmail", ctx="email", app="gmail",
            url=f"mailto:{msg.get('To', '')}", ts_iso=iso_from_epoch(ts), text=body,
        )
        if row:
            rows.append(row)
    conn.logout()
    return rows


# ---------------------------------------------------------------------------
# Loading into history + Chroma
# ---------------------------------------------------------------------------


def ingest(rows: list[dict], label_with_model: bool = True) -> None:
    known = corpus.history_ids()
    fresh, seen = [], set()
    for r in rows:
        if r["id"] in known or r["id"] in seen:
            continue
        seen.add(r["id"])
        fresh.append(r)
    print(f"{len(rows):,} candidate rows, {len(fresh):,} new")
    if not fresh:
        embed_missing({r["id"] for r in rows})
        return

    glossary = corpus.load_glossary()
    for r in fresh:
        corpus.enrich(r, glossary)
    pending = [r for r in fresh if not r.get("kind")]
    if pending and label_with_model:
        labels = corpus.classify_kinds_llm([r["text"] for r in pending])
        for r, label in zip(pending, labels):
            r["kind"] = label
    for r in fresh:
        r.setdefault("kind", "other")

    with config.HISTORY_JSONL.open("a", encoding="utf-8") as f:
        for r in fresh:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"Appended {len(fresh):,} rows to {config.HISTORY_JSONL.name}")
    embed_missing({r["id"] for r in rows})


def embed_missing(candidate_ids: set[str]) -> None:
    """Index every candidate row history knows and Chroma does not. Rows land
    in history before they are embedded, so a failed embedding run is repaired
    by running the ingest again."""
    import chromadb
    import retrieval
    coll = chromadb.PersistentClient(path=str(config.CHROMA_DIR)).get_or_create_collection(
        corpus.COLLECTION_NAME, metadata={"hnsw:space": "cosine"})
    existing = corpus.collection_ids(coll)
    eligible = [r for r in corpus.load_history()
                if r["id"] in candidate_ids and r["id"] not in existing
                and (r["words"] or 0) >= config.MIN_WORDS_FOR_INDEX]
    if not eligible:
        print("Nothing new to embed")
        return
    embed = retrieval.get_embedder()
    t0 = time.time()
    for i in range(0, len(eligible), BATCH):
        chunk = eligible[i:i + BATCH]
        coll.upsert(ids=[c["id"] for c in chunk], embeddings=embed([corpus.index_text(c) for c in chunk]),
                 documents=[corpus.index_text(c) for c in chunk],
                 metadatas=[corpus.build_metadata(c) for c in chunk])
        print(f"  {i + len(chunk):>6}/{len(eligible)}", end="\r")
    print(f"\nEmbedded {len(eligible):,} rows in {time.time() - t0:.0f}s; collection now {coll.count():,}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--whatsapp", action="store_true", help="Ingest the user's own WhatsApp messages")
    ap.add_argument("--gmail-work", metavar="USER", help="Ingest sent mail from a Workspace mailbox")
    ap.add_argument("--gmail-personal", action="store_true", help="Ingest sent mail from the personal Gmail (IMAP)")
    ap.add_argument("--gmail-account", help="Credentials name for --gmail-personal (default account when omitted)")
    ap.add_argument("--since-days", type=int, default=400, help="Look-back window for email (default 400)")
    ap.add_argument("--limit", type=int, default=5000, help="Max email rows per mailbox")
    ap.add_argument("--no-llm", action="store_true", help="Label kinds with rules only")
    args = ap.parse_args()
    if not (args.whatsapp or args.gmail_work or args.gmail_personal):
        ap.error("pick at least one source")

    rows: list[dict] = []
    if args.whatsapp:
        wa = whatsapp_rows(FEEDS_SQLITE, None)
        print(f"WhatsApp: {len(wa):,} messages from the user")
        rows += wa
    if args.gmail_work:
        gw = gmail_work_rows(args.gmail_work, args.since_days, args.limit)
        print(f"Gmail ({args.gmail_work}): {len(gw):,} sent messages with a body")
        rows += gw
    if args.gmail_personal:
        gp = gmail_personal_rows(args.since_days, args.limit, args.gmail_account)
        print(f"Gmail (personal): {len(gp):,} sent messages with a body")
        rows += gp
    ingest(rows, label_with_model=not args.no_llm)


if __name__ == "__main__":
    main()
